version: '3'
services:
  mysql:
    image: mysql:5.6
    container_name: mysql
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - 3306:3306