start:
	docker-compose up -db

end:
	docker-compose down

db:
	# パスワード        : mysql
	# db一覧           : show databases;
	# データベースを選択 : use <db name>;
	# table一覧        : shodow tables;
	# mysqlから抜ける   : exit
	docker exec -it mysql mysql -u root -p
